name: Hello AWS
on:
  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      
jobs:
  hello-world:
    name: Hello AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Hello AWS
        id: hello-aws
        uses: ExampleCoDept/fcc-demo-hello-world-core/hello-aws@main
        with:
          suffix: ${{ github.actor}}
